### ISSUE TITLE
Error in re-installing package

### ISSUE THREAD

**Issue by nelsonwongIFL** [EuropeanForestInstitute/tradeflows#3] opened 2016-05-21 02:52 UTC
Hi,

I've encountered a small problem in trying to re-installed the package. I'm running R under Windows 10. This is the error message I've received:

> devtools::install_github("paul4forest/tradeflows", build_vignettes = TRUE)
Downloading GitHub repo paul4forest/tradeflows@master
from URL https://api.github.com/repos/paul4forest/tradeflows/zipball/master
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Problem with the SSL CA cert (path? access rights?)
> vignette("visualisation", package ="tradeflows")
Warning message:
vignette ‘visualisation’ not found

**Comment by paul4forest** [comment] 2016-05-25 07:19
Follow Hadley's comment on [this related devtools issue](https://github.com/hadley/devtools/issues/1079) "Problem with the SSL CA cert ...": 
> Please restart R then install.packages(c("curl", "httr")) then try again.

For information, `paul4forest/tradeflows` is my personal repository, the official version is on `europeanforestinstitute/tradeflows`. I updated the install path in 92aa430. Try again with:
`install_github("EuropeanForestInstitute/tradeflows")`

**Comment by nelsonwongIFL** [comment] 2016-05-27 01:32
OK thanks Paul. Will keep you posted.

On Wed, May 25, 2016 at 3:19 PM, Paul Rougieux <notifications@github.com>
wrote:

> Follow Hadley's comment on this related devtools issue
> <https://github.com/hadley/devtools/issues/1079> "Problem with the SSL CA
> cert ...":
>
> Please restart R then install.packages(c("curl", "httr")) then try again.
>
> For information, paul4forest/tradeflows is my personal repository, the
> official version is on europeanforestinstitute/tradeflows. I updated the
> install path in 92aa430
> <https://github.com/EuropeanForestInstitute/tradeflows/commit/92aa430b3331ad7bc5f3706b6062d19e0f3bc547>.
> Try again with:
> install_github("EuropeanForestInstitute/tradeflows")
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/EuropeanForestInstitute/tradeflows/issues/3#issuecomment-221492883>
>



-- 
Nelson Wong

**Comment by paul4forest** [comment] 2016-06-08 11:55
Hello Nelson, did the proposed installation method fix your problem, can I close this issue?

**Comment by nelsonwongIFL** [comment] 2016-06-08 23:59
Hi Paul,

Thanks for getting back to me. I'm still having problems with the
installation fix. Could be a Windows 10 problem. I'm not sure. Am still
trying to work it out. Will certainly revert to you.

Sincerely,

Nelson Wong

On Wed, Jun 8, 2016 at 7:55 PM, Paul Rougieux <notifications@github.com>
wrote:

> Hello Nelson, did the proposed installation method fix your problem, can I
> close this issue?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/EuropeanForestInstitute/tradeflows/issues/3#issuecomment-224567361>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASmLWQrSCkjXXJGsbtyFgZS4aYR7ysadks5qJq2igaJpZM4Ijr1o>
> .
>



-- 
Nelson Wong

**Comment by nelsonwongIFL** [comment] 2016-06-09 04:42
Hi Paul,

I got this message while trying to re-install the package. Kindly advice.
Thanks.

> library(devtools)
> install_github("paul4forest/tradeflows", build_vignettes = TRUE)
Downloading GitHub repo paul4forest/tradeflows@master
from URL https://api.github.com/repos/paul4forest/tradeflows/zipball/master
Error in curl::curl_fetch_memory(url, handle = handle) :
  Problem with the SSL CA cert (path? access rights?)
> install_github("EuropeanForestInstitute/tradeflows", build_vignettes =
TRUE)
Downloading GitHub repo EuropeanForestInstitute/tradeflows@master
from URL
https://api.github.com/repos/EuropeanForestInstitute/tradeflows/zipball/master
Error in curl::curl_fetch_memory(url, handle = handle) :
  Problem with the SSL CA cert (path? access rights?)


Sincerely,

Nelson Wong

On Thu, Jun 9, 2016 at 7:59 AM, Nelson Wong <nelsonyswong@gmail.com> wrote:

> Hi Paul,
>
> Thanks for getting back to me. I'm still having problems with the
> installation fix. Could be a Windows 10 problem. I'm not sure. Am still
> trying to work it out. Will certainly revert to you.
>
> Sincerely,
>
> Nelson Wong
>
> On Wed, Jun 8, 2016 at 7:55 PM, Paul Rougieux <notifications@github.com>
> wrote:
>
>> Hello Nelson, did the proposed installation method fix your problem, can
>> I close this issue?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/EuropeanForestInstitute/tradeflows/issues/3#issuecomment-224567361>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ASmLWQrSCkjXXJGsbtyFgZS4aYR7ysadks5qJq2igaJpZM4Ijr1o>
>> .
>>
>
>
>
> --
> Nelson Wong
>



-- 
Nelson Wong

**Comment by paul4forest** [comment] 2016-06-09 07:36
I cannot reproduce your issue on a windows machine, using R 3.1.2 and Curl 0.9.7.

-  Could you paste the output of `sessionInfo()` please?

**Comment by nelsonwongIFL** [comment] 2016-06-10 01:49
Hi Paul,

I've enclosed a screen capture of the session. Hope this may be of help to
you.


Sincerely,

Nelson Wong

On Thu, Jun 9, 2016 at 3:36 PM, Paul Rougieux <notifications@github.com>
wrote:

> I cannot reproduce your issue on a windows machine, using R 3.1.2 and Curl
> 0.9.7.
>
>    - Could you paste the output of sessionInfo() please?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/EuropeanForestInstitute/tradeflows/issues/3#issuecomment-224821357>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASmLWR66SnaSdaTjG_LkXG1TITX3sD30ks5qJ8KGgaJpZM4Ijr1o>
> .
>



-- 
Nelson Wong

**Comment by paul4forest** [comment] 2016-06-10 06:43
I don't see the screen capture did you enter it on github? 
Please enter `sessionInfo()` at the R prompt and paste the output here.

**Comment by nelsonwongIFL** [comment] 2016-06-11 03:50
Hi Paul,

Good news. I think I've fixed the problem. I forgot to install the curl &
httr packages to begin with. My mistake. The installation looks good now.
Please see attached screen shot. Thanks & have a good weekend.


Sincerely,

Nelson Wong

On Thu, Jun 9, 2016 at 3:36 PM, Paul Rougieux <notifications@github.com>
wrote:

> I cannot reproduce your issue on a windows machine, using R 3.1.2 and Curl
> 0.9.7.
>
>    - Could you paste the output of sessionInfo() please?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/EuropeanForestInstitute/tradeflows/issues/3#issuecomment-224821357>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASmLWR66SnaSdaTjG_LkXG1TITX3sD30ks5qJ8KGgaJpZM4Ijr1o>
> .
>



-- 
Nelson Wong

**Comment by paul4forest** [comment] 2016-06-13 07:51
I cannot see your screenshot but since the installation works for you I'll close the issue now.

**Closed by paul4forest** 2016-06-13 07:51 UTC
